[theme]

primaryColor = '#B08F4C'
backgroundColor = '#F5F5F5'
secondaryBackgroundColor = '#D3E2F0'
textColor = '#000000'
font = "sans serif"


#B08F4C gold
#003a70 blue

#ffffff white
##F5F5F5 white Shieldy
#000000 black
#333333 grey

#f5f5dc cream white